const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Persist,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.NoSave,
		C3.Behaviors.Sin,
		C3.Plugins.Tilemap,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.TiledBg,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.sliderbar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Tilemap.Acts.SetPos,
		C3.Plugins.Tilemap.Acts.SetVisible,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.sliderbar.Acts.SetMinimum,
		C3.Plugins.sliderbar.Acts.SetMaximum,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Cnds.CompareInstanceVar,
		C3.Plugins.Button.Acts.AddInstanceVar,
		C3.Plugins.Button.Acts.SetInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.sliderbar.Acts.SetValue
	];
};
self.C3_JsPropNameTable = [
	{IsInvincible: 0},
	{InvincibilityDuration: 0},
	{"8Direction": 0},
	{Solid: 0},
	{ScrollTo: 0},
	{TileMovement: 0},
	{Char: 0},
	{Persist: 0},
	{CharSurf: 0},
	{Bullet: 0},
	{Bubble: 0},
	{FriendNPC: 0},
	{Health: 0},
	{Value: 0},
	{Pathfinding: 0},
	{Shark: 0},
	{Boat: 0},
	{Shopkeeper: 0},
	{Attack: 0},
	{Knocked: 0},
	{aChance: 0},
	{tChance: 0},
	{Teleport: 0},
	{BubbleColumnAmount: 0},
	{Boss: 0},
	{WeaponShopUITrig: 0},
	{DockUITrig: 0},
	{FriendNPCTrig: 0},
	{SpawnAmount: 0},
	{SpawnTimer: 0},
	{SpawnChance: 0},
	{SpawnValueMax: 0},
	{SpawnValueMin: 0},
	{SpawnHealth: 0},
	{InBossRoom: 0},
	{SpawnSpeed: 0},
	{NoSave: 0},
	{SharkSpawn: 0},
	{GetOut: 0},
	{FXGrass: 0},
	{InvisWall: 0},
	{FXWood: 0},
	{FXSand: 0},
	{BossLightTrigger: 0},
	{Exitplace: 0},
	{OilRigTrig: 0},
	{OilRig: 0},
	{BossMusicTrigger: 0},
	{AtlantisBlock: 0},
	{"2ExitPlace": 0},
	{WeaponShop: 0},
	{Exits: 0},
	{Wall: 0},
	{Money: 0},
	{Sine: 0},
	{Light: 0},
	{CharLight: 0},
	{BossLight: 0},
	{BossDoor: 0},
	{Damage: 0},
	{Spear: 0},
	{Crown: 0},
	{BossTrident: 0},
	{BossBubble: 0},
	{CaptureBubble: 0},
	{Timer: 0},
	{BossHealBubble: 0},
	{BubbleColumn: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Audio: 0},
	{AJAX: 0},
	{WeaponsData: 0},
	{OwnedWeapons: 0},
	{Level1Background: 0},
	{Level2Background: 0},
	{DocksBackground: 0},
	{Background: 0},
	{Level3Background: 0},
	{Level4Background: 0},
	{Level5Background: 0},
	{Level6Background: 0},
	{Level7Background: 0},
	{ShadowCaster: 0},
	{AtlantisBackground: 0},
	{AtlantisItems2: 0},
	{AtlantisItems1: 0},
	{JustWater: 0},
	{GameOverLose: 0},
	{GameOverWin: 0},
	{Tilemap: 0},
	{WeaponName: 0},
	{WeaponStats: 0},
	{Type: 0},
	{WeaponCost: 0},
	{ItemID: 0},
	{Cost: 0},
	{TimesBought: 0},
	{BuyWeapon: 0},
	{SelectButton: 0},
	{PlayerMoney: 0},
	{ShopName: 0},
	{GetIn: 0},
	{Buy: 0},
	{DockName: 0},
	{UIExit: 0},
	{UIB: 0},
	{ItemHolder: 0},
	{HealthIndex: 0},
	{HealthNode: 0},
	{InteractTooltip: 0},
	{HeathBar: 0},
	{Moneytxt: 0},
	{HealthBarAboveBottom: 0},
	{HealthBarBottom: 0},
	{HealthBarMiddle: 0},
	{HealthBarTop: 0},
	{Save: 0},
	{Load: 0},
	{MusicLevel: 0},
	{MusicMute: 0},
	{MusicVolume: 0},
	{SFXLevel: 0},
	{SFXMute: 0},
	{SFXVolume: 0},
	{PauseName: 0},
	{Return: 0},
	{GetInSub: 0},
	{Lore: 0},
	{InctructionsCard: 0},
	{instruct2: 0},
	{ButtonBackground: 0},
	{PlayText: 0},
	{InstructionsMenu: 0},
	{BackButton: 0},
	{Title: 0},
	{instruct: 0},
	{TiledBackground: 0},
	{CreditText: 0},
	{Text: 0},
	{GrayOutBackground: 0},
	{BossBar: 0},
	{Restart: 0},
	{Submirrored: 0},
	{Subangle: 0},
	{bubblechance: 0},
	{Heath: 0},
	{MaxHealth: 0},
	{WaterCraft: 0},
	{PrevPositionY: 0},
	{PrevPositionX: 0},
	{InWaterCraft: 0},
	{MiddleCount: 0},
	{SelectedWeaponID: 0},
	{CurrentEquippedWeapon: 0},
	{TridentLvl: 0},
	{HarpoonLvl: 0},
	{Boatsfxfix: 0},
	{UI: 0},
	{SpearAmount: 0},
	{CharRad: 0},
	{NotPaused: 0}
];

self.InstanceType = {
	Char: class extends self.ISpriteInstance {},
	CharSurf: class extends self.ISpriteInstance {},
	Bubble: class extends self.ISpriteInstance {},
	FriendNPC: class extends self.ISpriteInstance {},
	Shark: class extends self.ISpriteInstance {},
	Boat: class extends self.ISpriteInstance {},
	Shopkeeper: class extends self.ISpriteInstance {},
	Boss: class extends self.ISpriteInstance {},
	WeaponShopUITrig: class extends self.ISpriteInstance {},
	DockUITrig: class extends self.ISpriteInstance {},
	FriendNPCTrig: class extends self.ISpriteInstance {},
	SharkSpawn: class extends self.ISpriteInstance {},
	GetOut: class extends self.ISpriteInstance {},
	FXGrass: class extends self.ISpriteInstance {},
	InvisWall: class extends self.ISpriteInstance {},
	FXWood: class extends self.ISpriteInstance {},
	FXSand: class extends self.ISpriteInstance {},
	BossLightTrigger: class extends self.ISpriteInstance {},
	Exitplace: class extends self.ISpriteInstance {},
	OilRigTrig: class extends self.ISpriteInstance {},
	OilRig: class extends self.ISpriteInstance {},
	BossMusicTrigger: class extends self.ISpriteInstance {},
	AtlantisBlock: class extends self.ISpriteInstance {},
	_2ExitPlace: class extends self.ISpriteInstance {},
	WeaponShop: class extends self.ISpriteInstance {},
	Exits: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Money: class extends self.ISpriteInstance {},
	Light: class extends self.ISpriteInstance {},
	CharLight: class extends self.ISpriteInstance {},
	BossLight: class extends self.ISpriteInstance {},
	BossDoor: class extends self.ITilemapInstance {},
	Spear: class extends self.ISpriteInstance {},
	Crown: class extends self.ISpriteInstance {},
	BossTrident: class extends self.ISpriteInstance {},
	BossBubble: class extends self.ISpriteInstance {},
	CaptureBubble: class extends self.ISpriteInstance {},
	BossHealBubble: class extends self.ISpriteInstance {},
	BubbleColumn: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	WeaponsData: class extends self.IDictionaryInstance {},
	OwnedWeapons: class extends self.IDictionaryInstance {},
	Level1Background: class extends self.ITiledBackgroundInstance {},
	Level2Background: class extends self.ITiledBackgroundInstance {},
	DocksBackground: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Level3Background: class extends self.ISpriteInstance {},
	Level4Background: class extends self.ISpriteInstance {},
	Level5Background: class extends self.ISpriteInstance {},
	Level6Background: class extends self.ISpriteInstance {},
	Level7Background: class extends self.ISpriteInstance {},
	AtlantisBackground: class extends self.ITilemapInstance {},
	AtlantisItems2: class extends self.ITilemapInstance {},
	AtlantisItems1: class extends self.ITilemapInstance {},
	JustWater: class extends self.ISpriteInstance {},
	GameOverLose: class extends self.ISpriteInstance {},
	GameOverWin: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	WeaponName: class extends self.ITextInstance {},
	WeaponStats: class extends self.ITextInstance {},
	WeaponCost: class extends self.ITextInstance {},
	BuyWeapon: class extends self.IButtonInstance {},
	SelectButton: class extends self.IButtonInstance {},
	PlayerMoney: class extends self.ITextInstance {},
	ShopName: class extends self.ITextInstance {},
	GetIn: class extends self.IButtonInstance {},
	Buy: class extends self.IButtonInstance {},
	DockName: class extends self.ITextInstance {},
	UIExit: class extends self.ISpriteInstance {},
	UIB: class extends self.ISpriteInstance {},
	ItemHolder: class extends self.ISpriteInstance {},
	HealthNode: class extends self.ISpriteInstance {},
	InteractTooltip: class extends self.ITextInstance {},
	HeathBar: class extends self.ISpriteInstance {},
	Moneytxt: class extends self.ITextInstance {},
	HealthBarAboveBottom: class extends self.ISpriteInstance {},
	HealthBarBottom: class extends self.ISpriteInstance {},
	HealthBarMiddle: class extends self.ISpriteInstance {},
	HealthBarTop: class extends self.ISpriteInstance {},
	Save: class extends self.IButtonInstance {},
	Load: class extends self.IButtonInstance {},
	MusicLevel: class extends self.ITextInstance {},
	MusicMute: class extends self.ISpriteInstance {},
	MusicVolume: class extends self.ISliderBarInstance {},
	SFXLevel: class extends self.ITextInstance {},
	SFXMute: class extends self.ISpriteInstance {},
	SFXVolume: class extends self.ISliderBarInstance {},
	PauseName: class extends self.ITextInstance {},
	Return: class extends self.IButtonInstance {},
	GetInSub: class extends self.IButtonInstance {},
	Lore: class extends self.ITextInstance {},
	InctructionsCard: class extends self.ITiledBackgroundInstance {},
	instruct2: class extends self.ITextInstance {},
	ButtonBackground: class extends self.ISpriteInstance {},
	PlayText: class extends self.ITextInstance {},
	InstructionsMenu: class extends self.ITextInstance {},
	BackButton: class extends self.ITextInstance {},
	Title: class extends self.ISpriteInstance {},
	instruct: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	CreditText: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	GrayOutBackground: class extends self.ISpriteInstance {},
	BossBar: class extends self.ISpriteInstance {},
	Restart: class extends self.IButtonInstance {}
}